NameGen: NameGen Class Reference
NameGen Class Reference
#include <NameGen.hpp>
Public Member Functions
NameGen ()
Constructor that takes no arguments but requires 4 files in ./res/ : first.txt, last.txt, place.txt, and team.txt. Use this constructor when using NameGen from its own subdirectory.
NameGen (bool inDirectory)
Constructor that requires 4 files in ./res/ : first.txt, last.txt, place.txt, and team.txt. The value of inDirectory doesn't matter, it just signals that the application is being run from inside the nameGen directory so that the NameGen object will use the right file paths to get to the /res directory.
void populate ()
Called by constructors to populate the vectors with data from .txt files in res.
string genFirst ()
Member function that returns a random first name from firstBank.
string genLast ()
Member function that returns a random first name from lastBank.
string genFull ()
Member function that returns a single string containing "<firstname> <lastname>" pulled from genFirst() and genLast().
string genPlace ()
Member function that returns a random place name from placeBank.
string genTeam (bool withPlace)
Member function that has two functionalities based on boolean parameter. If withPlace is FALSE, the string returned will only be an element of teamBank. If withPlace is TRUE, the string will be in the format "<placename> <teamname>" with <placename> pulled from genPlace().
Private Attributes
string path1
string path2
string path3
string path4
Static Private Attributes
static vector< string > firstBank
static vector< string > lastBank
static vector< string > placeBank
static vector< string > teamBank
Detailed Description
Definition at line 20 of file NameGen.hpp.
Constructor & Destructor Documentation
NameGen::NameGen ()
Constructor that takes no arguments but requires 4 files in ./res/ : first.txt, last.txt, place.txt, and team.txt. Use this constructor when using NameGen from its own subdirectory.
Definition at line 16 of file NameGen.cpp.
References path1, path2, path3, path4, and populate().
                  {
   path1 = "./nameGen/res/first.txt";
   path2 = "./nameGen/res/last.txt";
   path3 = "./nameGen/res/team.txt";
   path4 = "./nameGen/res/place.txt";
   populate();
 }
NameGen::NameGen (bool inDirectory)
Constructor that requires 4 files in ./res/ : first.txt, last.txt, place.txt, and team.txt. The value of inDirectory doesn't matter, it just signals that the application is being run from inside the nameGen directory so that the NameGen object will use the right file paths to get to the /res directory.
Parameters
inDirectory Regardless of value passed will change filepath from "./nameGen/res/" to "./res/"
Definition at line 24 of file NameGen.cpp.
References path1, path2, path3, path4, and populate().
{
   path1 = "./res/first.txt";
   path2 = "./res/last.txt";
   path3 = "./res/team.txt";
   path4 = "./res/place.txt";
   populate();
 }
Member Function Documentation
string NameGen::genFirst ()
Member function that returns a random first name from firstBank.
Returns
std::string
Definition at line 85 of file NameGen.cpp.
References firstBank.
Referenced by genFull(), and main().
{
   int temp = rand() % firstBank.size();
   return firstBank[temp];
 }
string NameGen::genFull ()
Member function that returns a single string containing "<firstname> <lastname>" pulled from genFirst() and genLast().
Returns
std::string
Definition at line 95 of file NameGen.cpp.
References genFirst(), and genLast().
Referenced by main().
{
   return genFirst() + " " + genLast();
 }
string NameGen::genLast ()
Member function that returns a random first name from lastBank.
Returns
std::string
Definition at line 90 of file NameGen.cpp.
References firstBank, and lastBank.
Referenced by genFull(), and main().
{
   int temp = rand() % firstBank.size();
   return lastBank[temp];
 }
string NameGen::genPlace ()
Member function that returns a random place name from placeBank.
Returns
std::string
Definition at line 99 of file NameGen.cpp.
References placeBank.
Referenced by genTeam(), and main().
{
   int temp = rand() % placeBank.size();
   return placeBank[temp];
 }
string NameGen::genTeam (bool withPlace)
Member function that has two functionalities based on boolean parameter. If withPlace is FALSE, the string returned will only be an element of teamBank. If withPlace is TRUE, the string will be in the format "<placename> <teamname>" with <placename> pulled from genPlace().
Parameters
withPlace If true, team name will be appended to a place name. If false, only team name is returned.
Returns
std::string
Definition at line 104 of file NameGen.cpp.
References genPlace(), and teamBank.
Referenced by main().
{
   int temp = rand() % teamBank.size();
   string hold = teamBank[temp];
   if (withPlace) {
     return genPlace() + " " + hold;
   } else {
     return hold;
   }
 }
void NameGen::populate ()
Called by constructors to populate the vectors with data from .txt files in res.
Definition at line 32 of file NameGen.cpp.
References firstBank, lastBank, path1, path2, path3, path4, placeBank, and teamBank.
Referenced by NameGen().
                       {
   if(firstBank.size() > 0){
     printf("Already loaded\n");
     return;
   }
   ifstream inFile1(path1);
   ifstream inFile2(path2);
   ifstream inFile3(path3);
   ifstream inFile4(path4);
   string temp;
   if (inFile1.is_open()) {
       while (getline(inFile1, temp)) {
       firstBank.push_back(temp);
     }
       inFile1.close();
     } else {
       printf("Unable to open input file\n");
     }
   if (inFile2.is_open()) {
       while (getline(inFile2, temp)) {
       lastBank.push_back(temp);
     }
       inFile2.close();
     } else {
       printf("Unable to open input file\n");
     }
   if (inFile3.is_open()) {
       while (getline(inFile3, temp)) {
       teamBank.push_back(temp);
     }
       inFile3.close();
     } else {
       printf("Unable to open input file\n");
     }
   if (inFile4.is_open()) {
       while (getline(inFile4, temp)) {
       placeBank.push_back(temp);
     }
       inFile4.close();
     } else {
       printf("Unable to open input file\n");
     }
   firstBank.shrink_to_fit();
   lastBank.shrink_to_fit();
   teamBank.shrink_to_fit();
   placeBank.shrink_to_fit();
 }
Member Data Documentation
vector< string > NameGen::firstBank static private
NameGen.cpp Name generating object meant to be portable between projects
Author
Willis Hand
Version
1.2
Copyright
2017 Willis Hand
Definition at line 68 of file NameGen.hpp.
Referenced by genFirst(), genLast(), and populate().
vector< string > NameGen::lastBank static private
Definition at line 69 of file NameGen.hpp.
Referenced by genLast(), and populate().
string NameGen::path1 private
Definition at line 67 of file NameGen.hpp.
Referenced by NameGen(), and populate().
string NameGen::path2 private
Definition at line 67 of file NameGen.hpp.
Referenced by NameGen(), and populate().
string NameGen::path3 private
Definition at line 67 of file NameGen.hpp.
Referenced by NameGen(), and populate().
string NameGen::path4 private
Definition at line 67 of file NameGen.hpp.
Referenced by NameGen(), and populate().
vector< string > NameGen::placeBank static private
Definition at line 70 of file NameGen.hpp.
Referenced by genPlace(), and populate().
vector< string > NameGen::teamBank static private
Definition at line 71 of file NameGen.hpp.
Referenced by genTeam(), and populate().
The documentation for this class was generated from the following files:
NameGen.hpp
NameGen.cpp