NameGen: testGen.cpp File Reference
testGen.cpp File Reference
#include <iostream>
#include "NameGen.hpp"
Functions
int main ()
Function Documentation
int main ()
Definition at line 13 of file testGen.cpp.
References NameGen::genFirst(), NameGen::genFull(), NameGen::genLast(), NameGen::genPlace(), and NameGen::genTeam().
            {
   NameGen ng = NameGen();
   cout << "First: " << ng.genFirst() << "\n";
   cout << "Last:  " << ng.genLast() << "\n";
   cout << "Full:  " << ng.genFull() << "\n";
   cout << "Place: " << ng.genPlace() << "\n";
   cout << "Team:  " << ng.genTeam(false) << "\n";
   cout << "Team+: " << ng.genTeam(true) << "\n";
 }